# Generated by Django 4.1.7 on 2023-03-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("releaseTime", models.DateTimeField()),
                ("downTime", models.DateTimeField()),
                ("timeLength", models.IntegerField()),
                ("price", models.IntegerField()),
                ("screen", models.IntegerField()),
                (
                    "introduction",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("actor", models.CharField(blank=100, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userId", models.IntegerField()),
                ("filmName", models.CharField(max_length=100)),
                ("time", models.DateTimeField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleFilm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timing", models.DateTimeField()),
                ("monday", models.CharField(blank=100, max_length=100, null=True)),
                ("tuesday", models.CharField(blank=100, max_length=100, null=True)),
                ("wednesday", models.CharField(blank=100, max_length=100, null=True)),
                ("thursday", models.CharField(blank=100, max_length=100, null=True)),
                ("friday", models.CharField(blank=100, max_length=100, null=True)),
                ("saturday", models.CharField(blank=100, max_length=100, null=True)),
                ("sunday", models.CharField(blank=100, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("vipValidDate", models.DateTimeField()),
                ("state", models.IntegerField()),
            ],
        ),
    ]
