# Generated by Django 4.1.7 on 2023-03-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_user_vipvaliddate"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="screen",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
