# Generated by Django 4.1.7 on 2023-03-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_order_screen"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="state",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="orderState",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="film",
            name="actor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="schedulefilm",
            name="friday",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="schedulefilm",
            name="monday",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="schedulefilm",
            name="saturday",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="schedulefilm",
            name="sunday",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="schedulefilm",
            name="thursday",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="schedulefilm",
            name="tuesday",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="schedulefilm",
            name="wednesday",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
