# Generated by Django 4.1.7 on 2023-03-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_film_state_order_orderstate_alter_film_actor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="orderState", new_name="state",
        ),
    ]
