# Generated by Django 4.1.7 on 2023-03-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_rename_orderstate_order_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulefilm",
            name="timing",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
